[project]
name = "robot-tracker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "eventlet>=0.40.1",
    "flask>=3.1.1",
    "flask-socketio>=5.5.1",
    "psutil>=7.0.0",
    "requests>=2.32.4",
]
